services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=notification_db
    volumes:
      - mongo_data:/data/db

  notification-offer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-offer-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/notification_db
      - SECURITY_API_KEY=notification-service-secret-key
    depends_on:
      - mongodb

volumes:
  mongo_data:

  