server.port=8085
spring.application.name=notification-offer-service

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/notification_db

# Swagger UI configuration
springdoc.swagger-ui.path=/swagger-ui.html
