server.port=8084
spring.application.name=review-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27018/reviewdb

# API Key Security Configuration
api.key.secret=soc-secret-key-12345
api.key.header=X-API-KEY

# Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
